export const siteConfig = {
  name: "Urbana High School Class of 2006 Reunion",
  shortName: "UHS 2006 Reunion",
  dateLabel: "September 25 & 26, 2026",
  locationLabel: "Champaign & Urbana, Illinois",
  countdownTarget: "2026-09-25T17:00:00-05:00",
  contactEmail: "",
  facebookUrl: "",
};

export const events = [
  {
    id: "esquire",
    day: "Friday",
    month: "Sept",
    date: "25",
    year: "2026",
    eyebrow: "Night 1",
    title: "Esquire",
    city: "Champaign, Illinois",
    time: "5:00–8:00 PM",
    detail: "No cost to attend. Food and drinks are on your own tab.",
    mark: "E",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Esquire+Lounge+Champaign+Illinois",
  },
  {
    id: "school-tour",
    day: "Saturday",
    month: "Sept",
    date: "26",
    year: "2026",
    eyebrow: "School Event",
    title: "School Tour & Photo",
    city: "Urbana High School",
    time: "Details TBD",
    detail: "Take a walk down memory lane, tour Urbana High School, and join the class photo.",
    mark: "U",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Urbana+High+School+Urbana+Illinois",
  },
  {
    id: "riggs",
    day: "Saturday",
    month: "Sept",
    date: "26",
    year: "2026",
    eyebrow: "Night 2",
    title: "Riggs Beer Company",
    city: "Urbana, Illinois",
    time: "5:00–8:00 PM",
    detail: "No cost to attend. Indoor/outdoor patio; food and drinks are on your own tab.",
    mark: "R",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Riggs+Beer+Company+Urbana+Illinois",
  },
  {
    id: "cowboy-monkey",
    day: "Saturday",
    month: "Sept",
    date: "26",
    year: "2026",
    eyebrow: "Optional Night Out",
    title: "Cowboy Monkey",
    city: "Champaign, Illinois",
    time: "After the Riggs event",
    detail: "Stick around for an optional night out following the Riggs event.",
    mark: "CM",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Cowboy+Monkey+Champaign+Illinois",
  },
];
